# Generated by Django 3.2.13 on 2022-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registered_events',
            field=models.ManyToManyField(blank=True, related_name='registeredevents', to='events.Event'),
        ),
    ]
