# Generated by Django 3.2.13 on 2022-06-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_registered_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registered_events',
        ),
    ]
