# Generated by Django 3.2.13 on 2022-06-21 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_remove_profile_registered_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_teammates',
            field=models.ManyToManyField(blank=True, related_name='favoriteteammates', to=settings.AUTH_USER_MODEL),
        ),
    ]
