# Generated by Django 3.2.13 on 2022-06-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_users',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('1', 'Upcoming'), ('2', 'Active'), ('3', 'Done')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('1', 'Basketball'), ('2', 'Super Smash'), ('3', 'Freerunning')], default='1', max_length=50),
        ),
    ]
