# Generated by Django 3.2.13 on 2022-06-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_youtubevideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeVideo',
        ),
    ]
