# Generated by Django 3.2.13 on 2022-06-28 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_url', models.URLField()),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('occured', models.DateTimeField(default=datetime.datetime(2022, 6, 28, 22, 16, 22, 302073, tzinfo=utc))),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
