# Generated by Django 3.2.13 on 2022-06-28 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='occured',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
