# Generated by Django 3.2.13 on 2022-06-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20220628_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='bug_url',
            field=models.URLField(),
        ),
    ]
